version: '2.1'

  area 0.0.0.1 range aaaa:1:5::/64
  area 0.0.0.1 range aaaa:1:4::/64

  network 192.1.5.0/24 area 1
  network 192.1.4.0/24 area 1

services:
  r1:
    build: ./../images/ospf/.
    volumes:
      - ./../volumes/ospf/r1/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./../volumes/ospf/r1/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./../volumes/ospf/r1/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./../volumes/ospf/supervisord.conf:/etc/supervisord.conf:ro
    image: ospf:20180508
    privileged: true
    ports:
      #admin
      - 10111:2601
      #ospf ipv6
      - 10113:2606
    networks:
      r1_r2:
        ipv4_address: 192.1.5.3
        ipv6_address: aaaa:1:5::3
      # r1_r11:
      #   ipv4_address: 192.1.4.3
      #   ipv6_address: aaaa:1:4::3
          
  r2:
    build: ./../images/ospf/.
    image: ospf:20180508
    volumes:
      - ./../volumes/ospf/r2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./../volumes/ospf/r2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./../volumes/ospf/r2/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./../volumes/ospf/supervisord.conf:/etc/supervisord.conf:ro
    privileged: true
    ports:
      #admin
      - 10211:2601
      #ospf ipv6
      - 10213:2606
    networks:
      # r1_r2:
      #   ipv4_address: 192.1.5.2
      #   ipv6_address: aaaa:1:5::2
      r2_r22:
        ipv4_address: 192.1.6.3
        ipv6_address: aaaa:1:6::3

  # r11:
  #   build: ./../images/ospf/.
  #   image: ospf:20180508
  #   volumes:
  #     - ./../volumes/ospf/r11/zebra.conf:/etc/quagga/zebra.conf:ro
  #     - ./../volumes/ospf/r11/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
  #     - ./../volumes/ospf/r11/ospfd.conf:/etc/quagga/ospfd.conf:ro
  #     - ./../volumes/ospf/supervisord.conf:/etc/supervisord.conf:ro      
  #   privileged: true
  #   ports:
  #     #admin
  #     - 10121:2601
  #     #ospf ipv6
  #     - 10123:2606
  #   networks:
  #     r1_r11:
  #       ipv4_address: 192.1.4.2
  #       ipv6_address: aaaa:1:4::2
  #     r11_r12:
  #       ipv4_address: 192.1.3.2
  #       ipv6_address: aaaa:1:3::2
  #     r1_nginx:
  #       ipv4_address: 192.1.2.2
  #       ipv6_address: aaaa:1:2::2

  # r12:
  #   build: ./../images/ospf/.
  #   image: ospf:20180508
  #   volumes:
  #     - ./../volumes/ospf/r12/zebra.conf:/etc/quagga/zebra.conf:ro
  #     - ./../volumes/ospf/r12/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
  #     - ./../volumes/ospf/r12/ospfd.conf:/etc/quagga/ospfd.conf:ro
  #     - ./../volumes/ospf/supervisord.conf:/etc/supervisord.conf:ro
  #   privileged: true
  #   ports:
  #     #admin
  #     - 10131:2601
  #     #ospf ipv6
  #     - 10133:2606
  #   networks:
  #     r11_r12:
  #       ipv4_address: 192.1.3.3
  #       ipv6_address: aaaa:1:3::3
  #     r12_pc1:
  #       ipv4_address: 192.1.1.2
  #       ipv6_address: aaaa:1:1::2

  r21:
    build: ./../images/ospf/.
    image: ospf:20180508
    volumes:
      - ./../volumes/ospf/r21/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./../volumes/ospf/r21/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./../volumes/ospf/r21/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./../volumes/ospf/supervisord.conf:/etc/supervisord.conf:ro
    privileged: true
    ports:
      #admin
      - 10221:2601
      #ospf ipv6
      - 10223:2606
    networks:
      r22_r21:
        ipv4_address: 192.1.7.3
        ipv6_address: aaaa:1:7::3
      r21_pc2:
        ipv4_address: 192.1.9.2
        ipv6_address: aaaa:1:9::2

  r22:
    build: ./../images/ospf/.
    image: ospf:20180508
    volumes:
      - ./../volumes/ospf/r22/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./../volumes/ospf/r22/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./../volumes/ospf/r22/ospfd.conf:/etc/quagga/ospfd.conf:ro
      - ./../volumes/ospf/supervisord.conf:/etc/supervisord.conf:ro
    privileged: true
    ports:
      #admin
      - 10231:2601
      #ospf ipv6
      - 10233:2606
    networks:
      r2_r22:
        ipv4_address: 192.1.6.2
        ipv6_address: aaaa:1:6::2
      r22_r21:
        ipv4_address: 192.1.7.2
        ipv6_address: aaaa:1:7::2
      r22_apache:
        ipv4_address: 192.1.8.2
        ipv6_address: aaaa:1:8::2

  nginx:
    image:  nginx:1.15.10-alpine
    privileged: true
    ports:
      - 8080:80
    networks:
      r11_nginx:
        ipv4_address: 192.2.2.10
        ipv6_address: aaaa:2:2::10
  apache:
    image:  httpd:2.4.37-alpine
    ports:
      - 8081:80
    privileged: true
    networks:
      r22_apache:
        ipv4_address: 192.1.8.10
        ipv6_address: aaaa:1:8::10


networks:
  r1_r2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.1.5.0/24
        - subnet: aaaa:1:5::/64
  # r1_r11:
  #   driver: "bridge"
  #   enable_ipv6: true
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 192.1.4.0/24
  #       - subnet: aaaa:1:4::/64
  r2_r22:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.1.6.0/24
        - subnet: aaaa:1:6::/64
  # r11_r12:
  #   driver: "bridge"
  #   enable_ipv6: true
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 192.1.3.0/24
  #       - subnet: aaaa:1:3::/64
  # r11_gninx:
  #   driver: "bridge"
  #   enable_ipv6: true
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 192.1.2.0/24
  #       - subnet: aaaa:1:2::/64
  # r12_pc1:
  #   driver: "bridge"
  #   enable_ipv6: true
  #   ipam:
  #     driver: default
  #     config:
  #       - subnet: 192.1.1.0/24
  #       - subnet: aaaa:1:1::/64
  r22_r21:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.1.7.0/24
        - subnet: aaaa:1:7::/64
  r22_apache:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.1.8.0/24
        - subnet: aaaa:1:8::/64

  r21_pc2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 192.1.9.0/24
        - subnet: aaaa:1:9::/64


